### ISSUE TITLE
Sort login history DATE DESC by default

### ISSUE THREAD

**Issue by livinskull** [gizmore/gwf3#23]
The login history should  imho be sorted by date DESC instead of ASC by default - the most recent logins are the more important ones

**Comment by spaceone** [comment]
Fixed with https://github.com/gizmore/gwf3/commit/f97e9ccf50b037ae92389d065d0ef5daac4c6377. Thanks!

**Comment by spaceone** [comment]
Actually it was sorted by IP address prior ;-)
