### ISSUE TITLE
Ordering of linked sites by chall_solved

### ISSUE THREAD

**Issue by livinskull** [gizmore/gwf3#39]
On the [linked sites overview page](https://www.wechall.net/en/index.php?mo=WeChall&me=LinkedSites&by=regat_challsolved&dir=ASC) [1] sorting by _Solved_ does in fact sort by site name instead. It should sort by the solved column.

Clicking the column header does add `by=regat_challsolved` but it does not work.

**Comment by spaceone** [comment]
Hm, works for me? Or is the patch already applied?

**Comment by livinskull** [comment]
Might be confusing with 2 columns having the same name - I'm talking about the first one which sorts by _number of solved challs_, not the second one sorting by _percentage_

![2019-11-11_221601](https://user-images.githubusercontent.com/284406/68621833-fcd8d980-04d0-11ea-9bcf-ab0ffcd9acd8.png)

**Comment by spaceone** [comment]
Ah, thanks!
