### ISSUE TITLE
Shadowlamb Redmond hotelier link is down

### ISSUE THREAD

**Issue by livinskull** [gizmore/gwf3#82]
The second link given by the Hotelier in Redmond, when asking for **Renraku**, is down: `http://www.intercom.net/user/logan1/raku.htm`

Should probably be removed

**Comment by dloser** [comment]
Still available via http://web.archive.org/web/20160206013811/http://www.intercom.net/user/logan1/raku.htm (thx tehron). Could change the link to that.

**Comment by gizmore** [comment]
Changed to another / different link.
Closed with 852ee4fe

**Comment by tehron** [comment]
852ee4f seems to have duplicated the second link and removed the first.
