### ISSUE TITLE
Casting poison_dart crashes Dog.

### ISSUE THREAD

**Issue by dloser** [gizmore/gwf3#84]
Call to spellDamageSingleTarget doesn't match method signature:

https://github.com/gizmore/gwf3/blob/d04066514d4d3dc5ae9dc345e979a9d06ff3ca14/core/module/Dog/dog_modules/dog_module/Shadowlamb/spell/poison_dart.php#L24

https://github.com/gizmore/gwf3/blob/d04066514d4d3dc5ae9dc345e979a9d06ff3ca14/core/module/Dog/dog_modules/dog_module/Shadowlamb/core/SR_Spell.php#L364

(Probably want to swap order of key and damage parameters here...)

**Comment by gizmore** [comment]
Did not swap keys, but the idea is good. but now i don't care anymore after using your fix from production server.
Note that another crash occured then, in spell announcements.
See commit https://github.com/gizmore/gwf3/commit/5188cf18b4fd1e17d5c69728bb814f63a682a001
